environment:
  SH_VERSION_SUFFIX: 'preview'

  github_auth_token:
    secure: qOQatfN0omwlCj5Td82fK9Z3ZKQom0Nv3/x6OH98iB+L9mfOf26bH3q+PnQ7y7g7

configuration: Release

image: Visual Studio 2017

for:
- branches:
    only:
      - master
  environment:
    SH_VERSION_SUFFIX: ''

before_build:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { Set-AppveyorBuildVariable 'SH_VERSION_SUFFIX' 'alpha' }
  - dotnet tool install --global dotnet-sonarscanner --version 5.5.3
  - dotnet add "src/SignhostAPIClient.Tests/SignhostAPIClient.Tests.csproj" package coverlet.msbuild --version 3.1.0
  - cmd: dotnet restore "src\SignhostAPIClient.sln

build_script:
  - dotnet build "src\SignhostAPIClient.sln"
  - dotnet pack "src\SignhostAPIClient\SignhostAPIClient.csproj"

test_script:
  - dotnet test --no-build "src/SignhostAPIClient.Tests/SignhostAPIClient.Tests.csproj" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="./result.cover" /p:Exclude="[xunit*]*"

after_test:
  # No need for SonarScanner operation here

nuget:
  project_feed: true
  disable_publish_on_pr: false

artifacts:
  - path: '**\*.nupkg'
    name: Nuget

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/69c5136a745342743ec4
