environment:
  SH_VERSION_SUFFIX: 'preview'

  github_auth_token:
    secure: qOQatfN0omwlCj5Td82fK9Z3ZKQom0Nv3/x6OH98iB+L9mfOf26bH3q+PnQ7y7g7

configuration: Release

image: Visual Studio 2017

for:
- branches:
    only:
      - master
  environment:
    SH_VERSION_SUFFIX: ''

before_build:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { Set-AppveyorBuildVariable 'SH_VERSION_SUFFIX' 'alpha' }
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet add "src/SignhostAPIClient.Tests/SignhostAPIClient.Tests.csproj" package coverlet.msbuild
  - cmd: dotnet restore "src\SignhostAPIClient.sln

build_script:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER )                            { dotnet sonarscanner begin /k:"SignhostAPIClient" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=signhost" /d:"sonar.login=$env:sonarcloud_auth_token" /d:"sonar.cs.opencover.reportsPaths=src\SignhostAPIClient.Tests\result.cover" /d:"sonar.pullrequest.base=master" /d:"sonar.pullrequest.branch=PR-$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.pullrequest.key=$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.pullrequest.provider=GitHub" /d:"sonar.pullrequest.github.repository=Evidos/SignhostClientLibrary" }
  - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER)                        { dotnet sonarscanner begin /k:"SignhostAPIClient" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=signhost" /d:"sonar.login=$env:sonarcloud_auth_token" /d:"sonar.cs.opencover.reportsPaths=src\SignhostAPIClient.Tests\result.cover" }
  - dotnet build "src\SignhostAPIClient.sln"
  - dotnet pack "src\SignhostAPIClient\SignhostAPIClient.csproj"

test_script:
  - dotnet test --no-build "src/SignhostAPIClient.Tests/SignhostAPIClient.Tests.csproj" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="./result.cover"

after_test:
  - ps: dotnet sonarscanner end /d:"sonar.login=$env:sonarcloud_auth_token"; $LASTEXITCODE=0

nuget:
  project_feed: true
  disable_publish_on_pr: false

artifacts:
  - path: '**\*.nupkg'
    name: Nuget

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/69c5136a745342743ec4
