//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signhost.APIClient.Rest.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signhost.APIClient.Rest.Tests.APIResponses", typeof(APIResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Id&quot;: &quot;c487be92-0255-40c7-bd7d-20805a65e7d9&quot;,
        ///  &quot;Status&quot;: 20,
        ///  &quot;File&quot;: {
        ///    &quot;Id&quot;: &quot;d4bba0df-f9e5-44c8-89db-f2bb46632d7b&quot;,
        ///    &quot;Name&quot;: &quot;contract.pdf&quot;
        ///  },
        ///  &quot;Seal&quot;: true,
        ///  &quot;Signers&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;a2932c07-ca93-4011-96f5-a77d2cd1ec32&quot;,
        ///      &quot;Expires&quot;: null,
        ///      &quot;Email&quot;: &quot;user@example.com&quot;,
        ///      &quot;Mobile&quot;: &quot;+31612345678&quot;,
        ///      &quot;Iban&quot;: null,
        ///      &quot;BSN&quot;: null,
        ///      &quot;RequireScribbleName&quot;: false,
        ///      &quot;RequireScribble&quot;: true,
        ///      &quot;RequireEmailVerification&quot;: true,
        ///      &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Id&quot;: &quot;496bec4d-4ac7-428f-894a-b3e9bade725d&quot;,
        ///  &quot;Status&quot;: 20,
        ///  &quot;File&quot;: {
        ///    &quot;Id&quot;: &quot;3149bf06-d01e-4f0d-9aa1-77e100e19772&quot;,
        ///    &quot;Name&quot;: &quot;contract.pdf&quot;
        ///  },
        ///  &quot;Seal&quot;: true,
        ///  &quot;Signers&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;4813e178-68a4-4105-b007-5ce9a3630867&quot;,
        ///      &quot;Expires&quot;: null,
        ///      &quot;Email&quot;: &quot;user@example.com&quot;,
        ///      &quot;Mobile&quot;: &quot;+31612345678&quot;,
        ///      &quot;Iban&quot;: null,
        ///      &quot;BSN&quot;: null,
        ///      &quot;RequireScribbleName&quot;: false,
        ///      &quot;RequireScribble&quot;: true,
        ///      &quot;RequireEmailVerification&quot;: true,
        ///      &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteTransaction {
            get {
                return ResourceManager.GetString("DeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Id&quot;: &quot;c487be92-0255-40c7-bd7d-20805a65e7d9&quot;,
        ///  &quot;Status&quot;: 20,
        ///  &quot;File&quot;: {
        ///    &quot;Id&quot;: &quot;d4bba0df-f9e5-44c8-89db-f2bb46632d7b&quot;,
        ///    &quot;Name&quot;: &quot;contract.pdf&quot;
        ///  },
        ///  &quot;Seal&quot;: true,
        ///  &quot;Signers&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;a2932c07-ca93-4011-96f5-a77d2cd1ec32&quot;,
        ///      &quot;Expires&quot;: null,
        ///      &quot;Email&quot;: &quot;user@example.com&quot;,
        ///      &quot;Mobile&quot;: &quot;+31612345678&quot;,
        ///      &quot;Iban&quot;: null,
        ///      &quot;BSN&quot;: null,
        ///      &quot;RequireScribbleName&quot;: false,
        ///      &quot;RequireScribble&quot;: true,
        ///      &quot;RequireEmailVerification&quot;: true,
        ///      &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTransaction {
            get {
                return ResourceManager.GetString("GetTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Id&quot;: &quot;c487be92-0255-40c7-bd7d-20805a65e7d9&quot;,
        ///	&quot;Status&quot;: 20,
        ///	&quot;Seal&quot;: true,
        ///	&quot;Signers&quot;: [
        ///		{
        ///			&quot;Id&quot;: &quot;a2932c07-ca93-4011-96f5-a77d2cd1ec32&quot;,
        ///			&quot;Expires&quot;: null,
        ///			&quot;Email&quot;: &quot;user@example.com&quot;,
        ///			&quot;Mobile&quot;: &quot;+31612345678&quot;,
        ///			&quot;Iban&quot;: null,
        ///			&quot;BSN&quot;: null,
        ///			&quot;SendSignRequest&quot;: true,
        ///			&quot;SendSignConfirmation&quot;: null,
        ///			&quot;SignRequestMessage&quot;: &quot;Hello, could you please sign this document? Best regards, John Doe&quot;,
        ///			&quot;DaysToRemind&quot;: 15,
        ///			&quot;Language&quot;: &quot;en-US&quot;,
        ///			&quot;Reference&quot;: &quot;Client #123&quot;,
        ///			&quot;ReturnUrl&quot;: &quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTransactionCustomVerificationType {
            get {
                return ResourceManager.GetString("GetTransactionCustomVerificationType", resourceCulture);
            }
        }
    }
}
