//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signhost.APIClient.Rest.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequestBodies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestBodies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signhost.APIClient.Rest.Tests.RequestBodies", typeof(RequestBodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;DisplayOrder&quot;:null,&quot;DisplayName&quot;:null,&quot;Description&quot;:null,&quot;Signers&quot;:{&quot;someSignerId&quot;:{&quot;FormSets&quot;:[&quot;SampleFormSet&quot;]}},&quot;FormSets&quot;:{&quot;SampleFormSet&quot;:{&quot;SampleCheck&quot;:{&quot;Type&quot;:&quot;Check&quot;,&quot;Value&quot;:&quot;I agree&quot;,&quot;Location&quot;:{&quot;Search&quot;:&quot;test&quot;,&quot;Occurence&quot;:null,&quot;Top&quot;:null,&quot;Right&quot;:null,&quot;Bottom&quot;:null,&quot;Left&quot;:null,&quot;Width&quot;:null,&quot;Height&quot;:null,&quot;PageNumber&quot;:null}}}}}.
        /// </summary>
        internal static string AddOrReplaceFileMetaToTransaction {
            get {
                return ResourceManager.GetString("AddOrReplaceFileMetaToTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Id&quot;: &quot;50262c3f-9744-45bf-a4c6-8a3whatever&quot;,
        ///  &quot;Status&quot;: 5,
        ///  &quot;CanceledDateTime&quot;: &quot;2017-01-01 15:00&quot;,
        ///  &quot;Files&quot;: {},
        ///  &quot;Seal&quot;: false,
        ///  &quot;Signers&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;Signer1&quot;,
        ///      &quot;Email&quot;: &quot;test1@example.com&quot;,
        ///      &quot;Verifications&quot;: [
        ///        {
        ///          &quot;Type&quot;: &quot;PhoneNumber&quot;,
        ///          &quot;Number&quot;: &quot;+31615123456&quot;
        ///        }
        ///      ],
        ///      &quot;Mobile&quot;: &quot;+31615087075&quot;,
        ///      &quot;SignRequestMessage&quot;: &quot;Hello 1st signer&quot;,
        ///      &quot;Language&quot;: &quot;nl-NL&quot;,
        ///      &quot;Activities&quot;: [
        ///        {
        ///          &quot;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransactionSingleSignerJson {
            get {
                return ResourceManager.GetString("TransactionSingleSignerJson", resourceCulture);
            }
        }
    }
}
