name: Run Renovate

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          configurationFile: ../renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
